name = "ai-companion-web"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ai-companion-db"
database_id = "a4cdc18a-459f-4173-bee0-959f13986a6c"
